require "rake"

namespace :db do
  desc "add role base"
  task role_base: :environment do


    puts "delete"
    UserFunction.delete_all
    RoleFunction.delete_all
    Function.delete_all

    puts "create role base"

    role_trainer = Role.create name: "Role base trainer"
    role_trainer.functions.create!([
      {model_class: "trainer/dashboard", action: "index"},
      {model_class: "trainer/course_masters", action: "index"},
      {model_class: "trainer/course_masters", action: "create"},
      {model_class: "trainer/course_masters", action: "show"},
      {model_class: "trainer/course_masters", action: "update"},
      {model_class: "trainer/course_masters", action: "destroy"},
      {model_class: "trainer/subjects", action: "show"},
      {model_class: "trainer/course_subjects", action: "index"},
      {model_class: "trainer/course_subjects", action: "create"},
      {model_class: "trainer/course_subjects", action: "show"},
      {model_class: "trainer/course_subjects", action: "update"},
      {model_class: "trainer/course_subjects", action: "destroy"},
      {model_class: "trainer/courses", action: "index"},
      {model_class: "trainer/courses", action: "create"},
      {model_class: "trainer/courses", action: "show"},
      {model_class: "trainer/courses", action: "update"},
      {model_class: "trainer/courses", action: "destroy"},
      {model_class: "trainer/task_masters", action: "index"},
      {model_class: "trainer/subjects", action: "index"},
      {model_class: "trainer/subjects", action: "create"},
      {model_class: "trainer/subjects", action: "update"},
      {model_class: "trainer/subjects", action: "destroy"},
      {model_class: "trainer/users", action: "create"},
      {model_class: "trainer/users", action: "show"},
      {model_class: "trainer/users", action: "update"},
      {model_class: "trainer/users", action: "destroy"},
      {model_class: "trainer/feed_backs", action: "index"},
      {model_class: "trainer/user_subjects", action: "update"},
      {model_class: "trainer/tasks", action: "index"},
      {model_class: "trainer/tasks", action: "create"},
      {model_class: "trainer/tasks", action: "update"},
      {model_class: "trainer/tasks", action: "destroy"},
      {model_class: "trainer/allocate_permissions", action: "show"},
      {model_class: "trainer/allocate_permissions", action: "update"},
      {model_class: "trainer/allocate_permissions", action: "destroy"},
      {model_class: "trainer/allocate_permissions", action: "create"},
      {model_class: "trainer/roles", action: "index"},
      {model_class: "trainer/roles", action: "create"},
      {model_class: "trainer/roles", action: "show"},
      {model_class: "trainer/roles", action: "update"},
      {model_class: "trainer/roles", action: "destroy"},
      {model_class: "trainer/status_subjects", action: "update"},
      {model_class: "trainer/statistics", action: "show"},
      {model_class: "trainer/evaluation_templates", action: "index"},
      {model_class: "trainer/evaluation_templates", action: "create"},
      {model_class: "trainer/evaluation_templates", action: "show"},
      {model_class: "trainer/evaluation_templates", action: "update"},
      {model_class: "trainer/evaluation_templates", action: "destroy"},
      {model_class: "trainer/ranks", action: "index"},
      {model_class: "trainer/ranks", action: "create"},
      {model_class: "trainer/ranks", action: "show"},
      {model_class: "trainer/ranks", action: "update"},
      {model_class: "trainer/ranks", action: "destroy"},
      {model_class: "trainer/notes", action: "create"},
      {model_class: "trainer/notes", action: "show"},
      {model_class: "trainer/notes", action: "update"},
      {model_class: "trainer/notes", action: "destroy"},
      {model_class: "trainer/universities", action: "index"},
      {model_class: "trainer/universities", action: "create"},
      {model_class: "trainer/universities", action: "update"},
      {model_class: "trainer/universities", action: "destroy"},
      {model_class: "trainer/statuses", action: "index"},
      {model_class: "trainer/statuses", action: "create"},
      {model_class: "trainer/statuses", action: "update"},
      {model_class: "trainer/statuses", action: "destroy"},
      {model_class: "trainer/trainee_types", action: "index"},
      {model_class: "trainer/trainee_types", action: "create"},
      {model_class: "trainer/trainee_types", action: "update"},
      {model_class: "trainer/trainee_types", action: "destroy"},
      {model_class: "trainer/locations", action: "index"},
      {model_class: "trainer/locations", action: "create"},
      {model_class: "trainer/locations", action: "show"},
      {model_class: "trainer/locations", action: "update"},
      {model_class: "trainer/locations", action: "destroy"},
      {model_class: "trainer/organization_charts", action: "index"},
      {model_class: "trainer/training_managements", action: "index"},
      {model_class: "trainer/projects", action: "index"},
      {model_class: "trainer/projects", action: "create"},
      {model_class: "trainer/projects", action: "show"},
      {model_class: "trainer/projects", action: "update"},
      {model_class: "trainer/projects", action: "destroy"},
      {model_class: "trainer/programs", action: "index"},
      {model_class: "trainer/programs", action: "create"},
      {model_class: "trainer/programs", action: "show"},
      {model_class: "trainer/programs", action: "update"},
      {model_class: "trainer/statistics", action: "index"},
      {model_class: "trainer/statistics", action: "create"},
      {model_class: "trainer/trainee_evaluations", action: "index"},
      {model_class: "trainer/trainee_evaluations", action: "create"},
      {model_class: "trainer/trainee_evaluations", action: "show"},
      {model_class: "trainer/trainee_evaluations", action: "update"},
      {model_class: "trainer/user_courses", action: "update"},
      {model_class: "trainer/user_subjects", action: "index"},
      {model_class: "trainer/user_subjects", action: "create"},
      {model_class: "trainer/user_subjects", action: "show"},
      {model_class: "trainer/user_subjects", action: "destroy"},
      {model_class: "trainer/evaluation_standards", action: "index"},
      {model_class: "trainer/evaluation_standards", action: "create"},
      {model_class: "trainer/evaluation_standards", action: "show"},
      {model_class: "trainer/evaluation_standards", action: "update"},
      {model_class: "trainer/evaluation_standards", action: "destroy"}
    ])

    role_trainee = Role.create name: "Role base trainee"
    role_trainee.functions.create!([
      {model_class: "Course", action: "read"},
      {model_class: "CourseSubject", action: "read"},
      {model_class: "Evaluation", action: "read"},
      {model_class: "Evaluation", action: "create"},
      {model_class: "Evaluation", action: "update"},
      {model_class: "Evaluation", action: "destroy"},
      {model_class: "Note", action: "read"},
      {model_class: "Note", action: "create"},
      {model_class: "Note", action: "update"},
      {model_class: "Note", action: "destroy"},
      {model_class: "Notification", action: "read"},
      {model_class: "Notification", action: "create"},
      {model_class: "Subject", action: "read"},
      {model_class: "User", action: "read"},
      {model_class: "UserCourse", action: "read"},
      {model_class: "UserSubject", action: "update"},
      {model_class: "FeedBack", action: "read"},
      {model_class: "Course", action: "read"},
      {model_class: "Subject", action: "read"},
      {model_class: "Task", action: "read"},
      {model_class: "Task", action: "create"},
      {model_class: "Task", action: "update"},
      {model_class: "Task", action: "destroy"},
      {model_class: "User", action: "read"},
      {model_class: "UserCourse", action: "read"},
      {model_class: "UserSubject", action: "update"},
      {model_class: "UserTask", action: "read"},
      {model_class: "UserTask", action: "create"},
      {model_class: "UserTask", action: "update"},
      {model_class: "UserTask", action: "destroy"},
      {model_class: "FeedBack", action: "create"},
      {model_class: "User", action: "create"},
      {model_class: "User", action: "update"},
      {model_class: "User", action: "destroy"},
      {model_class: "Answer", action: "read"},
      {model_class: "Answer", action: "update"},
      {model_class: "Exam", action: "read"},
      {model_class: "Exam", action: "update"},
      {model_class: "Question", action: "read"},
      {model_class: "Question", action: "update"},
      {model_class: "Result", action: "read"},
      {model_class: "Result", action: "update"},
      {model_class: "Answer", action: "read"},
      {model_class: "Exam", action: "read"},
      {model_class: "Question", action: "read"},
      {model_class: "Result", action: "read"},
      {model_class: "Result", action: "update"},
      {model_class: "Answer", action: "read"},
      {model_class: "Answer", action: "update"},
      {model_class: "Exam", action: "read"},
      {model_class: "Exam", action: "update"},
      {model_class: "Question", action: "read"},
      {model_class: "Question", action: "update"},
      {model_class: "Result", action: "read"},
      {model_class: "Result", action: "update"},
      {model_class: "Answer", action: "read"},
      {model_class: "Exam", action: "read"},
      {model_class: "Question", action: "read"},
      {model_class: "Result", action: "read"},
      {model_class: "Result", action: "update"},
      {model_class: "Exam", action: "update"},
      {model_class: "Course", action: "create"},
      {model_class: "Course", action: "update"},
      {model_class: "Course", action: "destroy"},
      {model_class: "subjects", action: "show"},
      {model_class: "courses", action: "index"},
      {model_class: "courses", action: "show"},
      {model_class: "course_subjects", action: "index"},
      {model_class: "course_subjects", action: "create"},
      {model_class: "course_subjects", action: "show"},
      {model_class: "course_subjects", action: "update"},
      {model_class: "course_subjects", action: "destroy"},
      {model_class: "profiles", action: "show"},
      {model_class: "profiles", action: "update"},
      {model_class: "profiles", action: "destroy"},
      {model_class: "profiles", action: "create"},
      {model_class: "users", action: "show"},
      {model_class: "users", action: "update"},
      {model_class: "user_courses", action: "show"},
      {model_class: "tasks", action: "index"},
      {model_class: "tasks", action: "create"},
      {model_class: "tasks", action: "show"},
      {model_class: "tasks", action: "update"},
      {model_class: "tasks", action: "destroy"},
      {model_class: "user_subjects", action: "update"},
      {model_class: "user_tasks", action: "show"},
      {model_class: "user_tasks", action: "update"},
      {model_class: "feed_backs", action: "create"},
      {model_class: "exams", action: "index"},
      {model_class: "exams", action: "show"},
      {model_class: "exams", action: "update"},
      {model_class: "change_current_role_types", action: "update"},
      {model_class: "comments", action: "index"},
      {model_class: "comments", action: "create"},
      {model_class: "comments", action: "show"},
      {model_class: "comments", action: "update"},
      {model_class: "comments", action: "destroy"},
      {model_class: "votes", action: "create"},
      {model_class: "votes", action: "destroy"},
      {model_class: "posts", action: "index"},
      {model_class: "posts", action: "create"},
      {model_class: "posts", action: "show"},
      {model_class: "posts", action: "update"},
      {model_class: "posts", action: "destroy"},
      {model_class: "tags", action: "index"},
      {model_class: "tags", action: "show"},
      {model_class: "timelines", action: "index"}
    ])

    puts "create function"
    Rails.application.routes.routes.anchored_routes.map(&:defaults)
      .reject {|route| route[:internal] || Settings.controller_names.include?(route[:controller])}
      .each do |route|
      Function.find_or_create_by model_class: route[:controller],
        action: route[:action] unless route[:action] == "edit" || route[:action] == "new"
    end
  end
end
